// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web2Project.Baza;

#nullable disable

namespace Web2Project.Migrations
{
    [DbContext(typeof(CRUD_Context))]
    partial class CRUD_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Web2Project.Models.Korisnik", b =>
                {
                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImeIPrezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Novac")
                        .HasColumnType("float");

                    b.Property<string>("Slika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipKoorisnika")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("Verifikovan")
                        .HasColumnType("bit");

                    b.HasKey("Email");

                    b.ToTable("Korisnik");
                });

            modelBuilder.Entity("Web2Project.Models.Paket", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Cena")
                        .HasColumnType("float");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PorudzbinaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Slika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PorudzbinaId");

                    b.ToTable("Paket");
                });

            modelBuilder.Entity("Web2Project.Models.Porudzbina", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Cena")
                        .HasColumnType("float");

                    b.Property<string>("Informacija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<string>("KorisnikEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KorisnikEmail1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KupacId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdavacId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VremeDostave")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikEmail");

                    b.HasIndex("KorisnikEmail1");

                    b.ToTable("Porudzbina");
                });

            modelBuilder.Entity("Web2Project.Models.Paket", b =>
                {
                    b.HasOne("Web2Project.Models.Porudzbina", null)
                        .WithMany("Artikli")
                        .HasForeignKey("PorudzbinaId");
                });

            modelBuilder.Entity("Web2Project.Models.Porudzbina", b =>
                {
                    b.HasOne("Web2Project.Models.Korisnik", null)
                        .WithMany("NovePorudzbine")
                        .HasForeignKey("KorisnikEmail");

                    b.HasOne("Web2Project.Models.Korisnik", null)
                        .WithMany("PredhodnePorudzbine")
                        .HasForeignKey("KorisnikEmail1");
                });

            modelBuilder.Entity("Web2Project.Models.Korisnik", b =>
                {
                    b.Navigation("NovePorudzbine");

                    b.Navigation("PredhodnePorudzbine");
                });

            modelBuilder.Entity("Web2Project.Models.Porudzbina", b =>
                {
                    b.Navigation("Artikli");
                });
#pragma warning restore 612, 618
        }
    }
}
